#include "../core/internal.h"
#include "laststate/envelope.h"

#define TLV_IDENTITY LS_TLV_IDENTITY
#define TLV_RESET LS_TLV_RESET
#define TLV_EVENT LS_TLV_EVENT
#define TLV_CPU LS_TLV_CPU
#define TLV_FAULT LS_TLV_FAULT
#define TLV_BREADCRUMB LS_TLV_BREADCRUMB
#define TLV_METRIC LS_TLV_METRIC
#define TLV_POWER LS_TLV_POWER
#define TLV_HEALTH LS_TLV_HEALTH
#define TLV_ASSERT LS_TLV_ASSERT
#define TLV_PERIPHERAL LS_TLV_PERIPHERAL
#define TLV_LOG LS_TLV_LOG
#define TLV_MEMORY LS_TLV_MEMORY
#define TLV_STACK LS_TLV_STACK
#define TLV_HEAP LS_TLV_HEAP
static uint16_t read_u16(const uint8_t *p){return (uint16_t)p[0]|((uint16_t)p[1]<<8);}
static uint32_t read_u32(const uint8_t *p){return (uint32_t)p[0]|((uint32_t)p[1]<<8)|((uint32_t)p[2]<<16)|((uint32_t)p[3]<<24);}
static ls_result_t put_string_field(ls_writer_t *writer,uint8_t field,const char *text){size_t length=ls_string_length(text);if(length>255)length=255;ls_result_t result=ls_writer_u8(writer,field);if(result==LS_OK)result=ls_writer_u8(writer,(uint8_t)length);if(result==LS_OK)result=ls_writer_write(writer,text,length);return result;}
static ls_result_t put_identity(ls_writer_t *writer){
    const ls_identity_t *identity=ls_runtime.config.identity;uint8_t value[512];ls_writer_t nested={value,sizeof value,0};
    const char *build=identity->firmware_build_id?identity->firmware_build_id:ls_build_id();
    const char *fields[]={identity->project_id,identity->device_id,identity->product,identity->hardware_revision,identity->bom_revision,identity->manufacturing_batch,identity->firmware_version,build,identity->bootloader_version,identity->git_commit,identity->variant,identity->architecture?identity->architecture:0,identity->rtos?identity->rtos:ls_runtime.config.rtos,identity->region?identity->region:ls_runtime.config.region,identity->device_group?identity->device_group:ls_runtime.config.device_group};
    for(uint8_t i=0;i<15;i++){ls_result_t result=put_string_field(&nested,(uint8_t)(i+1),fields[i]);if(result!=LS_OK)return result;}
    return ls_writer_tlv(writer,TLV_IDENTITY,value,(uint16_t)nested.length);
}
static ls_result_t put_reset(ls_writer_t *writer,const ls_event_t *event){uint8_t value[32];ls_writer_t nested={value,sizeof value,0};ls_result_t result=ls_writer_u8(&nested,(uint8_t)ls_runtime.reset_info.reason);if(result==LS_OK)result=ls_writer_u32(&nested,ls_runtime.reset_info.raw_reason);if(result==LS_OK)result=ls_writer_u32(&nested,ls_runtime.boot_count);if(result==LS_OK)result=ls_writer_u32(&nested,ls_runtime.reset_info.previous_uptime_ms);if(result==LS_OK)result=ls_writer_u32(&nested,event->timestamp_ms);if(result==LS_OK)result=ls_writer_u8(&nested,ls_runtime.reset_info.expected?1:0);if(result==LS_OK)result=ls_writer_u8(&nested,ls_runtime.previous_crashed?1:0);if(result==LS_OK)result=ls_writer_u8(&nested,ls_runtime.boot_loop?1:0);return result==LS_OK?ls_writer_tlv(writer,TLV_RESET,value,(uint16_t)nested.length):result;}
static ls_result_t put_event(ls_writer_t *writer,const ls_event_t *event){uint8_t value[64];ls_writer_t nested={value,sizeof value,0};ls_result_t result=ls_writer_u8(&nested,(uint8_t)event->priority);if(result==LS_OK)result=ls_writer_u8(&nested,(uint8_t)event->severity);if(result==LS_OK)result=ls_writer_u8(&nested,(uint8_t)event->capture_level);if(result==LS_OK)result=ls_writer_u32(&nested,ls_hash_string(event->domain));if(result==LS_OK)result=ls_writer_u32(&nested,(uint32_t)event->code);if(result==LS_OK)result=ls_writer_u32(&nested,event->message?ls_hash_string(event->message):0);if(result==LS_OK)result=ls_writer_u32(&nested,event->fingerprint);if(result==LS_OK)result=ls_writer_u32(&nested,event->repeat_count);if(result==LS_OK)result=ls_writer_u32(&nested,event->first_seen_ms);if(result==LS_OK)result=ls_writer_u32(&nested,event->last_seen_ms);return result==LS_OK?ls_writer_tlv(writer,TLV_EVENT,value,(uint16_t)nested.length):result;}
static ls_result_t put_cpu(ls_writer_t *writer,const ls_arch_context_t *cpu){
    if(!cpu)return LS_OK;uint8_t value[512];ls_writer_t nested={value,sizeof value,0};ls_result_t result=ls_writer_u8(&nested,(uint8_t)cpu->architecture);if(result==LS_OK)result=ls_writer_u8(&nested,(uint8_t)cpu->fault);for(unsigned i=0;i<32&&result==LS_OK;i++)result=ls_writer_u32(&nested,cpu->registers[i]);
    const uint32_t special[]={cpu->lr,cpu->pc,cpu->xpsr,cpu->msp,cpu->psp,cpu->control,cpu->primask,cpu->basepri,cpu->faultmask,cpu->exc_return,cpu->mcause,cpu->mtval,cpu->mstatus,cpu->mepc,cpu->exccause,cpu->excvaddr,cpu->ps,cpu->sar};
    for(size_t i=0;i<sizeof special/sizeof special[0]&&result==LS_OK;i++)result=ls_writer_u32(&nested,special[i]);if(result==LS_OK)result=ls_writer_u8(&nested,cpu->has_fpu?1:0);if(result==LS_OK)result=ls_writer_u8(&nested,cpu->fpu_lazy?1:0);if(cpu->has_fpu)for(unsigned i=0;i<16&&result==LS_OK;i++)result=ls_writer_u32(&nested,cpu->s[i]);if(cpu->has_fpu&&result==LS_OK)result=ls_writer_u32(&nested,cpu->fpscr);if(result!=LS_OK)return result;result=ls_writer_tlv(writer,TLV_CPU,value,(uint16_t)nested.length);if(result!=LS_OK)return result;
uint8_t fault[64];ls_writer_t fault_writer={fault,sizeof fault,0};const uint32_t status[]={cpu->cfsr,cpu->hfsr,cpu->dfsr,cpu->afsr,cpu->mmfar,cpu->bfar,cpu->shcsr,cpu->icsr,cpu->vtor,cpu->sfsr,cpu->sfar,(uint32_t)cpu->fault_address,(uint32_t)cpu->signal_number};for(size_t i=0;i<sizeof status/sizeof status[0];i++)if((result=ls_writer_u32(&fault_writer,status[i]))!=LS_OK)return result;return ls_writer_tlv(writer,TLV_FAULT,fault,(uint16_t)fault_writer.length);
}
static ls_result_t put_breadcrumbs(ls_writer_t *writer){
#if LS_ENABLE_BREADCRUMBS
    for(size_t n=0;n<ls_runtime.breadcrumb_count;n++){size_t index=(ls_runtime.breadcrumb_next+LS_BREADCRUMB_CAPACITY-ls_runtime.breadcrumb_count+n)%LS_BREADCRUMB_CAPACITY;ls_breadcrumb_record_t *record=&ls_runtime.breadcrumbs[index];uint8_t value[160];ls_writer_t nested={value,sizeof value,0};ls_result_t result=ls_writer_u32(&nested,record->at_ms);if(result==LS_OK)result=ls_writer_u16(&nested,record->message_id);if(result==LS_OK)result=ls_writer_u8(&nested,record->severity);if(result==LS_OK)result=ls_writer_u32(&nested,record->category_hash);if(result==LS_OK)result=ls_writer_u32(&nested,record->message_hash);
#if LS_STORE_STRINGS
        if(result==LS_OK)result=put_string_field(&nested,1,record->category);if(result==LS_OK)result=put_string_field(&nested,2,record->message);
#endif
        if(result==LS_OK)result=ls_writer_u8(&nested,record->value_count);for(uint8_t k=0;k<record->value_count&&result==LS_OK;k++){result=ls_writer_u16(&nested,record->values[k].key_id);if(result==LS_OK)result=ls_writer_u8(&nested,(uint8_t)record->values[k].type);if(result==LS_OK)result=ls_writer_u32(&nested,record->values[k].value.u32);}if(result!=LS_OK)return result;result=ls_writer_tlv(writer,TLV_BREADCRUMB,value,(uint16_t)nested.length);if(result==LS_ENOSPACE)return LS_OK;if(result!=LS_OK)return result;}
#else
    (void)writer;
#endif
    return LS_OK;
}
static ls_result_t put_metrics(ls_writer_t *writer){
#if LS_ENABLE_METRICS
    for(size_t i=0;i<ls_runtime.metric_count;i++){ls_metric_record_t *metric=&ls_runtime.metrics[i];uint8_t value[128];ls_writer_t nested={value,sizeof value,0};ls_result_t result=ls_writer_u32(&nested,metric->name_hash);
#if LS_STORE_STRINGS
        if(result==LS_OK)result=put_string_field(&nested,1,metric->name);
#endif
        if(result==LS_OK)result=ls_writer_u8(&nested,metric->type);if(result==LS_OK)result=ls_writer_u32(&nested,(uint32_t)metric->value);if(result==LS_OK)result=ls_writer_u32(&nested,(uint32_t)metric->previous);if(result==LS_OK)result=ls_writer_u32(&nested,(uint32_t)metric->minimum);if(result==LS_OK)result=ls_writer_u32(&nested,(uint32_t)metric->maximum);if(result==LS_OK)result=ls_writer_u64(&nested,(uint64_t)metric->sum);if(result==LS_OK)result=ls_writer_u32(&nested,metric->count);if(result==LS_OK)result=ls_writer_u8(&nested,metric->window_count);for(uint8_t w=0;w<metric->window_count&&result==LS_OK;w++)result=ls_writer_u32(&nested,(uint32_t)metric->window[w]);if(result!=LS_OK)return result;result=ls_writer_tlv(writer,TLV_METRIC,value,(uint16_t)nested.length);if(result==LS_ENOSPACE)return LS_OK;if(result!=LS_OK)return result;}
#else
    (void)writer;
#endif
    return LS_OK;
}
static ls_result_t put_power_health(ls_writer_t *writer){for(size_t n=0;n<ls_runtime.power_count;n++){size_t index=(ls_runtime.power_next+LS_POWER_SAMPLE_CAPACITY-ls_runtime.power_count+n)%LS_POWER_SAMPLE_CAPACITY;ls_power_sample_t *sample=&ls_runtime.power_samples[index];uint8_t value[20];ls_writer_t nested={value,sizeof value,0};(void)ls_writer_u32(&nested,sample->timestamp_ms);(void)ls_writer_u16(&nested,sample->vdd_mv);(void)ls_writer_u16(&nested,sample->battery_mv);(void)ls_writer_u16(&nested,(uint16_t)sample->current_ma);(void)ls_writer_u16(&nested,(uint16_t)sample->temperature_c);(void)ls_writer_u16(&nested,sample->charger_status);(void)ls_writer_u16(&nested,sample->power_flags);ls_result_t result=ls_writer_tlv(writer,TLV_POWER,value,(uint16_t)nested.length);if(result==LS_ENOSPACE)return LS_OK;if(result!=LS_OK)return result;}uint8_t health[32];ls_writer_t nested={health,sizeof health,0};(void)ls_writer_u32(&nested,ls_runtime.watchdog_last_feed);(void)ls_writer_u16(&nested,ls_runtime.watchdog_checkpoint);(void)ls_writer_u32(&nested,ls_hash_string(ls_runtime.active_task));return ls_writer_tlv(writer,TLV_HEALTH,health,(uint16_t)nested.length);}
static ls_result_t put_details(ls_writer_t *writer,const ls_event_t *event){
    if(event->assertion){uint8_t value[200];ls_writer_t nested={value,sizeof value,0};(void)ls_writer_u32(&nested,(uint32_t)event->assertion->line);(void)ls_writer_u32(&nested,ls_hash_string(event->assertion->expression));(void)ls_writer_u32(&nested,ls_hash_string(event->assertion->file));
#if LS_STORE_STRINGS
        (void)put_string_field(&nested,1,event->assertion->expression);(void)put_string_field(&nested,2,event->assertion->file);(void)put_string_field(&nested,3,event->assertion->message);
#endif
        ls_result_t result=ls_writer_tlv(writer,TLV_ASSERT,value,(uint16_t)nested.length);if(result!=LS_OK)return result;}
    if(event->peripheral){uint8_t value[48];ls_writer_t nested={value,sizeof value,0};(void)ls_writer_u8(&nested,(uint8_t)event->peripheral->domain);(void)ls_writer_u16(&nested,event->peripheral->fault);(void)ls_writer_u16(&nested,event->peripheral->instance);(void)ls_writer_u32(&nested,event->peripheral->status);(void)ls_writer_u32(&nested,event->peripheral->address);(void)ls_writer_u32(&nested,event->peripheral->reg);(void)ls_writer_u32(&nested,event->peripheral->timeout_ms);for(unsigned i=0;i<4;i++)(void)ls_writer_u32(&nested,event->peripheral->auxiliary[i]);ls_result_t result=ls_writer_tlv(writer,TLV_PERIPHERAL,value,(uint16_t)nested.length);if(result!=LS_OK)return result;}
    if(event->log){uint8_t value[24];ls_writer_t nested={value,sizeof value,0};(void)ls_writer_u16(&nested,event->log->message_id);(void)ls_writer_u16(&nested,event->log->format_id);(void)ls_writer_u8(&nested,event->log->argument_count);for(uint8_t i=0;i<event->log->argument_count;i++)(void)ls_writer_u32(&nested,event->log->arguments[i]);ls_result_t result=ls_writer_tlv(writer,TLV_LOG,value,(uint16_t)nested.length);if(result!=LS_OK)return result;}return LS_OK;
}
static ls_result_t put_memory(ls_writer_t *writer,const ls_event_t *event){
#if LS_ENABLE_DUMPS
    if(event->capture_level<LS_CAPTURE_SELECTIVE)return LS_OK;for(size_t i=0;i<ls_runtime.dump_region_count;i++){const ls_dump_region_t *region=&ls_runtime.dump_regions[i];if(!(region->flags&LS_DUMP_SAFE))continue;size_t length=region->length>LS_DUMP_REGION_MAX_BYTES?LS_DUMP_REGION_MAX_BYTES:region->length;bool matched=false;ls_redaction_mode_t mode=ls_redaction_for(region->address,length,&matched);if(matched&&mode==LS_REDACT_EXCLUDE)continue;uint8_t value[LS_DUMP_REGION_MAX_BYTES+48];ls_writer_t nested={value,sizeof value,0};(void)ls_writer_u32(&nested,ls_hash_string(region->name));(void)ls_writer_u32(&nested,(uint32_t)(uintptr_t)region->address);(void)ls_writer_u32(&nested,(uint32_t)region->length);(void)ls_writer_u32(&nested,region->flags);if(matched&&mode==LS_REDACT_HASH){(void)ls_writer_u32(&nested,ls_crc32(region->address,length));}else if(matched&&mode==LS_REDACT_ZERO){uint8_t zero[32]={0};size_t remaining=length;while(remaining){size_t chunk=remaining>sizeof zero?sizeof zero:remaining;if(ls_writer_write(&nested,zero,chunk)!=LS_OK)break;remaining-=chunk;}}else{(void)ls_writer_write(&nested,region->address,length);}ls_result_t result=ls_writer_tlv(writer,TLV_MEMORY,value,(uint16_t)nested.length);if(result==LS_ENOSPACE)return LS_OK;if(result!=LS_OK)return result;}
    if(event->capture_level>=LS_CAPTURE_STACK&&event->cpu&&ls_runtime.stack_lower&&ls_runtime.stack_upper){uintptr_t sp=event->cpu->psp?event->cpu->psp:event->cpu->msp;if(sp>=(uintptr_t)ls_runtime.stack_lower&&sp<(uintptr_t)ls_runtime.stack_upper){size_t length=(size_t)((uintptr_t)ls_runtime.stack_upper-sp);if(length>LS_STACK_SNAPSHOT_MAX)length=LS_STACK_SNAPSHOT_MAX;uint8_t value[LS_STACK_SNAPSHOT_MAX+8];ls_writer_t nested={value,sizeof value,0};(void)ls_writer_u32(&nested,(uint32_t)sp);(void)ls_writer_u32(&nested,(uint32_t)length);(void)ls_writer_write(&nested,(const void *)sp,length);ls_result_t result=ls_writer_tlv(writer,TLV_STACK,value,(uint16_t)nested.length);if(result!=LS_OK&&result!=LS_ENOSPACE)return result;}}
#else
    (void)writer;(void)event;
#endif
    uint8_t heap[20];ls_writer_t nested={heap,sizeof heap,0};(void)ls_writer_u32(&nested,ls_runtime.heap_stats.free_bytes);(void)ls_writer_u32(&nested,ls_runtime.heap_stats.minimum_free_bytes);(void)ls_writer_u32(&nested,ls_runtime.heap_stats.largest_block);(void)ls_writer_u32(&nested,ls_runtime.heap_stats.allocation_failures);(void)ls_writer_u32(&nested,ls_runtime.heap_stats.pool_exhaustions);return ls_writer_tlv(writer,TLV_HEAP,heap,(uint16_t)nested.length);
}
ls_result_t ls_envelope_encode(const ls_event_t *event,uint8_t *out,size_t capacity,size_t *length){
    bool secured=ls_runtime.security_key_length!=0;bool aead=secured&&ls_runtime.security_policy.algorithm==LS_SECURITY_XCHACHA20_POLY1305;size_t metadata_size=aead?LS_ENVELOPE_SECURITY_METADATA_SIZE:0u;size_t authentication_size=secured?(aead?LS_AEAD_TAG_SIZE:LS_HMAC_SHA256_SIZE):0u;
    if(!event||!out||!length||capacity<LS_LEP_HEADER_SIZE+metadata_size+4u+authentication_size)return LS_EINVAL;
    uint32_t sequence=++ls_runtime.sequence;
    ls_writer_t payload={out+LS_LEP_HEADER_SIZE+metadata_size,capacity-LS_LEP_HEADER_SIZE-metadata_size-4u-authentication_size,0};
    ls_result_t result=put_identity(&payload);if(result==LS_OK)result=put_reset(&payload,event);if(result==LS_OK)result=put_event(&payload,event);if(result==LS_OK)result=put_cpu(&payload,event->cpu);if(result==LS_OK)result=put_details(&payload,event);if(result==LS_OK)result=put_breadcrumbs(&payload);if(result==LS_OK)result=put_metrics(&payload);if(result==LS_OK)result=put_power_health(&payload);if(result==LS_OK)result=put_memory(&payload,event);if(result!=LS_OK){ls_secure_zero(out,LS_LEP_HEADER_SIZE+metadata_size+payload.length);return result;}
    uint32_t event_id=ls_crc32(out+LS_LEP_HEADER_SIZE+metadata_size,payload.length)^sequence^ls_hash_string(ls_build_id());
    uint8_t header[LS_LEP_HEADER_SIZE];ls_writer_t header_writer={header,sizeof header,0};
    uint8_t flags=secured?LS_ENVELOPE_AUTHENTICATED:0u;if(aead)flags|=LS_ENVELOPE_ENCRYPTED|LS_ENVELOPE_AEAD;
    (void)ls_writer_u32(&header_writer,LS_MAGIC);(void)ls_writer_u8(&header_writer,LS_PROTOCOL_VERSION);(void)ls_writer_u8(&header_writer,(uint8_t)event->type);(void)ls_writer_u8(&header_writer,(uint8_t)(event->cpu?event->cpu->architecture:ls_runtime.config.architecture));(void)ls_writer_u8(&header_writer,flags);(void)ls_writer_u32(&header_writer,sequence);(void)ls_writer_u32(&header_writer,event_id);(void)ls_writer_u32(&header_writer,(uint32_t)payload.length);(void)ls_writer_u32(&header_writer,ls_crc32(header,20));
    ls_memcpy(out,header,sizeof header);
    if(aead){
        uint8_t *nonce=out+LS_LEP_HEADER_SIZE;ls_result_t random_result=ls_security_random(nonce,LS_XCHACHA20_NONCE_SIZE);if(random_result!=LS_OK){ls_secure_zero(out,LS_LEP_HEADER_SIZE+metadata_size+payload.length);return random_result;}if(ls_runtime.has_last_envelope_nonce&&ls_constant_time_equal(nonce,ls_runtime.last_envelope_nonce,LS_XCHACHA20_NONCE_SIZE)){ls_secure_zero(out,LS_LEP_HEADER_SIZE+metadata_size+payload.length);return LS_EAUTH;}uint32_t key_id=ls_runtime.security_policy.key_id;nonce[24]=(uint8_t)key_id;nonce[25]=(uint8_t)(key_id>>8);nonce[26]=(uint8_t)(key_id>>16);nonce[27]=(uint8_t)(key_id>>24);
        uint8_t derived[32];static const uint8_t label[]="laststate/latch/envelope/v1";uint8_t salt[12]={(uint8_t)key_id,(uint8_t)(key_id>>8),(uint8_t)(key_id>>16),(uint8_t)(key_id>>24),(uint8_t)sequence,(uint8_t)(sequence>>8),(uint8_t)(sequence>>16),(uint8_t)(sequence>>24),(uint8_t)event_id,(uint8_t)(event_id>>8),(uint8_t)(event_id>>16),(uint8_t)(event_id>>24)};ls_result_t derive=ls_hkdf_sha256(salt,sizeof salt,ls_runtime.security_key,ls_runtime.security_key_length,label,sizeof label-1u,derived,sizeof derived);if(derive!=LS_OK){ls_secure_zero(out,LS_LEP_HEADER_SIZE+metadata_size+payload.length);return derive;}
        uint8_t *ciphertext=out+LS_LEP_HEADER_SIZE+metadata_size;size_t crc_offset=LS_LEP_HEADER_SIZE+metadata_size+payload.length;uint8_t *tag=out+crc_offset+4u;ls_result_t encrypted=ls_xchacha20_poly1305_encrypt(derived,nonce,out,LS_LEP_HEADER_SIZE+metadata_size,ciphertext,ciphertext,payload.length,tag);ls_secure_zero(derived,sizeof derived);if(encrypted!=LS_OK){ls_secure_zero(out,crc_offset+4u+authentication_size);return encrypted;}
        uint32_t payload_crc=ls_crc32(out+LS_LEP_HEADER_SIZE,metadata_size+payload.length);out[crc_offset]=(uint8_t)payload_crc;out[crc_offset+1]=(uint8_t)(payload_crc>>8);out[crc_offset+2]=(uint8_t)(payload_crc>>16);out[crc_offset+3]=(uint8_t)(payload_crc>>24);ls_memcpy(ls_runtime.last_envelope_nonce,nonce,LS_XCHACHA20_NONCE_SIZE);ls_runtime.has_last_envelope_nonce=true;*length=crc_offset+4u+authentication_size;
    }else{
        uint32_t payload_crc=ls_crc32(out+LS_LEP_HEADER_SIZE,payload.length);size_t crc_offset=LS_LEP_HEADER_SIZE+payload.length;out[crc_offset]=(uint8_t)payload_crc;out[crc_offset+1]=(uint8_t)(payload_crc>>8);out[crc_offset+2]=(uint8_t)(payload_crc>>16);out[crc_offset+3]=(uint8_t)(payload_crc>>24);size_t total=crc_offset+4u;if(authentication_size){ls_hmac_sha256(ls_runtime.security_key,ls_runtime.security_key_length,out,total,out+total);total+=authentication_size;}*length=total;
    }
    ls_runtime.persistent.last_sequence=sequence;return LS_OK;
}
ls_result_t ls_envelope_validate(const uint8_t *data,size_t length,ls_envelope_info_t *info){if(!data)return LS_EINVAL;if(length<LS_LEP_HEADER_SIZE+4u||read_u32(data)!=LS_MAGIC||data[4]!=LS_PROTOCOL_VERSION)return LS_ECORRUPT;uint8_t flags=data[7];bool encrypted=(flags&LS_ENVELOPE_ENCRYPTED)!=0;if((flags&LS_ENVELOPE_AEAD)&&!encrypted)return LS_ECORRUPT;if(encrypted&&(!(flags&LS_ENVELOPE_AEAD)||!(flags&LS_ENVELOPE_AUTHENTICATED)))return LS_ECORRUPT;size_t metadata_size=encrypted?LS_ENVELOPE_SECURITY_METADATA_SIZE:0u;size_t authentication_size=encrypted?LS_AEAD_TAG_SIZE:((flags&LS_ENVELOPE_AUTHENTICATED)?LS_HMAC_SHA256_SIZE:0u);uint32_t payload_length=read_u32(data+16);size_t overhead=LS_LEP_HEADER_SIZE+metadata_size+4u+authentication_size;if(length<overhead||payload_length>length-overhead||length!=overhead+payload_length)return LS_ECORRUPT;size_t crc_offset=LS_LEP_HEADER_SIZE+metadata_size+payload_length;if(read_u32(data+20)!=ls_crc32(data,20)||read_u32(data+crc_offset)!=ls_crc32(data+LS_LEP_HEADER_SIZE,metadata_size+payload_length))return LS_ECORRUPT;if(info){info->version=data[4];info->type=data[5];info->architecture=data[6];info->flags=flags;info->sequence=read_u32(data+8);info->event_id=read_u32(data+12);info->payload_length=payload_length;}return LS_OK;}
static ls_result_t visit_payload(const uint8_t *payload,size_t payload_length,ls_tlv_visitor_t visitor,void *context){if(!visitor)return LS_EINVAL;size_t offset=0;while(offset<payload_length){if(payload_length-offset<4u)return LS_ECORRUPT;uint16_t type=read_u16(payload+offset),field_length=read_u16(payload+offset+2);offset+=4u;if(field_length>payload_length-offset)return LS_ECORRUPT;ls_result_t result=visitor(context,type,payload+offset,field_length);if(result!=LS_OK)return result;offset+=field_length;}return LS_OK;}
ls_result_t ls_envelope_decrypt_payload(const uint8_t *data,size_t length,uint8_t *plaintext,size_t capacity,size_t *plaintext_length){ls_envelope_info_t info;if(!plaintext_length)return LS_EINVAL;ls_result_t result=ls_envelope_validate(data,length,&info);if(result!=LS_OK)return result;if(!(info.flags&LS_ENVELOPE_ENCRYPTED)||!(info.flags&LS_ENVELOPE_AEAD)||!ls_runtime.security_key_length)return LS_EAUTH;if(plaintext&&capacity<info.payload_length)return LS_ENOSPACE;if(!plaintext&&capacity)return LS_EINVAL;const uint8_t *nonce=data+LS_LEP_HEADER_SIZE;uint32_t key_id=read_u32(nonce+24);if(key_id!=ls_runtime.security_policy.key_id)return LS_EAUTH;uint8_t derived[32];static const uint8_t label[]="laststate/latch/envelope/v1";uint32_t sequence=info.sequence,event_id=info.event_id;uint8_t salt[12]={(uint8_t)key_id,(uint8_t)(key_id>>8),(uint8_t)(key_id>>16),(uint8_t)(key_id>>24),(uint8_t)sequence,(uint8_t)(sequence>>8),(uint8_t)(sequence>>16),(uint8_t)(sequence>>24),(uint8_t)event_id,(uint8_t)(event_id>>8),(uint8_t)(event_id>>16),(uint8_t)(event_id>>24)};result=ls_hkdf_sha256(salt,sizeof salt,ls_runtime.security_key,ls_runtime.security_key_length,label,sizeof label-1u,derived,sizeof derived);if(result==LS_OK){const uint8_t *ciphertext=data+LS_LEP_HEADER_SIZE+LS_ENVELOPE_SECURITY_METADATA_SIZE;const uint8_t *tag=ciphertext+info.payload_length+4u;result=ls_xchacha20_poly1305_decrypt(derived,nonce,data,LS_LEP_HEADER_SIZE+LS_ENVELOPE_SECURITY_METADATA_SIZE,ciphertext,plaintext,info.payload_length,tag);}ls_secure_zero(derived,sizeof derived);if(result==LS_OK)*plaintext_length=info.payload_length;else if(plaintext)ls_secure_zero(plaintext,capacity);return result;}
ls_result_t ls_envelope_visit(const uint8_t *data,size_t length,ls_tlv_visitor_t visitor,void *context){ls_envelope_info_t info;ls_result_t result=ls_envelope_validate(data,length,&info);if(result!=LS_OK)return result;if(info.flags&LS_ENVELOPE_ENCRYPTED)return LS_EAUTH;return visit_payload(data+LS_LEP_HEADER_SIZE,info.payload_length,visitor,context);}
ls_result_t ls_envelope_visit_secure(const uint8_t *data,size_t length,uint8_t *workspace,size_t workspace_size,ls_tlv_visitor_t visitor,void *context){ls_envelope_info_t info;ls_result_t result=ls_envelope_validate(data,length,&info);if(result!=LS_OK)return result;if(!(info.flags&LS_ENVELOPE_ENCRYPTED)){if(info.flags&LS_ENVELOPE_AUTHENTICATED){result=ls_envelope_verify_auth(data,length);if(result!=LS_OK)return result;}else if(ls_security_enabled()&&ls_runtime.security_policy.reject_plaintext)return LS_EAUTH;return visit_payload(data+LS_LEP_HEADER_SIZE,info.payload_length,visitor,context);}size_t plaintext_length=0;result=ls_envelope_decrypt_payload(data,length,workspace,workspace_size,&plaintext_length);if(result!=LS_OK)return result;result=visit_payload(workspace,plaintext_length,visitor,context);ls_secure_zero(workspace,plaintext_length);return result;}
