#include <stdio.h>
#include <string.h>
#include "laststate/latch.h"
#define CHECK(x) do{if(!(x)){fprintf(stderr,"security check failed: %s:%d\n",#x,__LINE__);return 1;}}while(0)
static uint8_t retained[50000],sent[LS_MAX_EVENT_SIZE];static size_t sent_length;
static int equal_hex(const uint8_t *data,const char *hex,size_t length){static const char digits[]="0123456789abcdef";for(size_t i=0;i<length;i++)if(digits[data[i]>>4]!=hex[i*2]||digits[data[i]&15]!=hex[i*2+1])return 0;return 1;}
static bool available(void *x){(void)x;return true;}static size_t mtu(void *x){(void)x;return LS_MAX_EVENT_SIZE;}static ls_result_t send_data(void *x,const uint8_t *data,size_t length){(void)x;memcpy(sent,data,length);sent_length=length;return LS_OK;}
static ls_result_t random_bytes(void *context,uint8_t *output,size_t length){uint32_t *state=(uint32_t *)context;for(size_t i=0;i<length;i++){*state=*state*1664525u+1013904223u;output[i]=(uint8_t)(*state>>24);}return LS_OK;}
static ls_result_t count_tlv(void *context,uint16_t type,const uint8_t *value,uint16_t length){(void)type;(void)value;(void)length;(*(unsigned *)context)++;return LS_OK;}
int main(void){uint8_t key[20],digest[32];memset(key,0x0b,sizeof key);ls_hmac_sha256(key,sizeof key,(const uint8_t *)"Hi There",8,digest);CHECK(equal_hex(digest,"b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7",32));uint8_t chacha_key[32],nonce[12]={0,0,0,9,0,0,0,0x4a,0,0,0,0},stream[64];for(unsigned i=0;i<32;i++)chacha_key[i]=(uint8_t)i;ls_chacha20_xor(chacha_key,nonce,1,0,stream,sizeof stream);CHECK(equal_hex(stream,"10f1e7e4d13b5915500fdd1fa32071c4c7d1f4c733c068030422aa9ac3d46c4ed2826446079faa0914c2d705d98b02a2b5129cd1de164eb9cbd083e8a2503c4e",64));CHECK(ls_replay_accept(10));CHECK(!ls_replay_accept(10));CHECK(ls_replay_accept(9));CHECK(!ls_replay_accept(9));CHECK(ls_replay_accept(100));CHECK(!ls_replay_accept(1));
ls_identity_t identity={.project_id="security",.device_id="one",.firmware_build_id="security01"};ls_config_t config={.identity=&identity};ls_memory_storage_t memory={retained,sizeof retained};ls_storage_backend_t storage={.name="memory",.context=&memory,.capacity=sizeof retained,.read=ls_memory_storage_read,.write=ls_memory_storage_write,.erase=ls_memory_storage_erase};ls_transport_backend_t transport={.name="sink",.priority=1,.available=available,.send=send_data,.max_payload=mtu};CHECK(ls_init(&config)==LS_OK);ls_storage_register(&storage);ls_transport_register(&transport);CHECK(ls_boot()==LS_OK);uint32_t random_state=1;ls_security_set_random_provider(random_bytes,&random_state);CHECK(ls_security_set_key(chacha_key,sizeof chacha_key)==LS_OK);ls_capture_message("authenticated",LS_SEVERITY_ERROR);CHECK(ls_flush()==LS_OK);CHECK(sent_length>LS_AEAD_TAG_SIZE&&ls_envelope_verify_auth(sent,sent_length)==LS_OK);uint8_t plaintext[LS_MAX_EVENT_SIZE];size_t plaintext_length=0;CHECK(ls_envelope_decrypt_payload(sent,sent_length,plaintext,sizeof plaintext,&plaintext_length)==LS_OK);CHECK(plaintext_length>0);CHECK(ls_envelope_visit(sent,sent_length,count_tlv,0)==LS_EAUTH);unsigned tlvs=0;memset(plaintext,0xa5,sizeof plaintext);CHECK(ls_envelope_visit_secure(sent,sent_length,plaintext,sizeof plaintext,count_tlv,&tlvs)==LS_OK);CHECK(tlvs>0);for(size_t i=0;i<plaintext_length;i++)CHECK(plaintext[i]==0);sent[sent_length-1]^=1u;CHECK(ls_envelope_validate(sent,sent_length,0)==LS_OK);CHECK(ls_envelope_verify_auth(sent,sent_length)==LS_EAUTH);ls_security_clear_key();CHECK(!ls_security_enabled());return 0;}
