set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_COMPILER riscv64-unknown-elf-gcc)
set(CMAKE_CXX_COMPILER riscv64-unknown-elf-g++)
set(CMAKE_ASM_COMPILER riscv64-unknown-elf-gcc)
set(CMAKE_C_FLAGS_INIT "-march=rv64imac_zicsr -mabi=lp64 -ffunction-sections -fdata-sections")
set(CMAKE_CXX_FLAGS_INIT "-march=rv64imac_zicsr -mabi=lp64 -fno-exceptions -fno-rtti -ffunction-sections -fdata-sections")
set(CMAKE_ASM_FLAGS_INIT "-march=rv64imac_zicsr -mabi=lp64")
set(LS_BUILD_RISCV64 ON CACHE BOOL "" FORCE)
set(LS_ENABLE_WIDE_CONTEXT ON CACHE BOOL "" FORCE)
set(LS_BUILD_TESTS OFF CACHE BOOL "" FORCE)
