#include "../core/internal.h"
#include "laststate/flash_storage.h"
#define FLASH_MAGIC 0x464d534cu
#define FLASH_COMMITTED 0xa5u
typedef struct {uint32_t magic,generation,data_crc,header_crc;uint8_t committed,reserved[15];} flash_header_t;
static size_t aligned(size_t value,size_t alignment){return alignment?((value+alignment-1u)/alignment)*alignment:value;}
size_t ls_flash_mirror_physical_size(size_t logical_capacity,size_t erase_size){return 2u*aligned(sizeof(flash_header_t)+logical_capacity,erase_size?erase_size:1u);}
static size_t bank_offset(const ls_flash_mirror_t *mirror,uint8_t bank){return (size_t)bank*mirror->bank_size;}
static uint32_t header_crc(const flash_header_t *header){return ls_crc32(header,offsetof(flash_header_t,header_crc));}
static ls_result_t raw_read(ls_flash_mirror_t *mirror,size_t offset,void *dst,size_t length){return mirror->raw->read(mirror->raw->context,offset,dst,length);}
static bool valid_bank(ls_flash_mirror_t *mirror,uint8_t bank,flash_header_t *header){size_t offset=bank_offset(mirror,bank);if(raw_read(mirror,offset,header,sizeof *header)!=LS_OK||header->magic!=FLASH_MAGIC||header->committed!=FLASH_COMMITTED||header->header_crc!=header_crc(header))return false;if(raw_read(mirror,offset+sizeof *header,mirror->workspace,mirror->logical_capacity)!=LS_OK)return false;return header->data_crc==ls_crc32(mirror->workspace,mirror->logical_capacity);}
static ls_result_t commit_image(ls_flash_mirror_t *mirror,uint8_t bank,uint32_t generation){size_t offset=bank_offset(mirror,bank);ls_result_t result=mirror->raw->erase(mirror->raw->context,offset,mirror->bank_size);if(result!=LS_OK)return result;flash_header_t header;ls_memset(&header,0xff,sizeof header);header.magic=FLASH_MAGIC;header.generation=generation;header.data_crc=ls_crc32(mirror->workspace,mirror->logical_capacity);header.header_crc=header_crc(&header);result=mirror->raw->write(mirror->raw->context,offset,&header,sizeof header);if(result==LS_OK)result=mirror->raw->write(mirror->raw->context,offset+sizeof header,mirror->workspace,mirror->logical_capacity);if(result==LS_OK){uint8_t committed=FLASH_COMMITTED;result=mirror->raw->write(mirror->raw->context,offset+offsetof(flash_header_t,committed),&committed,1);}if(result==LS_OK&&mirror->raw->sync)result=mirror->raw->sync(mirror->raw->context);if(result==LS_OK){mirror->active_bank=bank;mirror->generation=generation;}return result;}
static ls_result_t mirror_read(void *context,size_t offset,void *dst,size_t length){ls_flash_mirror_t *mirror=(ls_flash_mirror_t *)context;if(!mirror||(!dst&&length)||offset>mirror->logical_capacity||length>mirror->logical_capacity-offset)return LS_EINVAL;return raw_read(mirror,bank_offset(mirror,mirror->active_bank)+sizeof(flash_header_t)+offset,dst,length);}
static ls_result_t update_image(ls_flash_mirror_t *mirror,size_t offset,const void *src,size_t length,bool erase){if(!mirror||(!erase&&!src&&length)||offset>mirror->logical_capacity||length>mirror->logical_capacity-offset)return LS_EINVAL;ls_result_t result=raw_read(mirror,bank_offset(mirror,mirror->active_bank)+sizeof(flash_header_t),mirror->workspace,mirror->logical_capacity);if(result!=LS_OK)return result;if(erase)ls_memset(mirror->workspace+offset,0xff,length);else if(length)ls_memcpy(mirror->workspace+offset,src,length);return commit_image(mirror,(uint8_t)(mirror->active_bank^1u),mirror->generation+1u);}
static ls_result_t mirror_write(void *context,size_t offset,const void *src,size_t length){return (!src&&length)?LS_EINVAL:update_image((ls_flash_mirror_t *)context,offset,src,length,false);}
static ls_result_t mirror_erase(void *context,size_t offset,size_t length){return update_image((ls_flash_mirror_t *)context,offset,0,length,true);}
static ls_result_t mirror_sync(void *context){ls_flash_mirror_t *mirror=(ls_flash_mirror_t *)context;return mirror->raw->sync?mirror->raw->sync(mirror->raw->context):LS_OK;}
ls_result_t ls_flash_mirror_init(ls_flash_mirror_t *mirror,ls_storage_backend_t *raw,uint8_t *workspace,size_t logical_capacity){if(!mirror||!raw||!raw->read||!raw->write||!raw->erase||!workspace||!logical_capacity)return LS_EINVAL;ls_memset(mirror,0,sizeof *mirror);mirror->raw=raw;mirror->workspace=workspace;mirror->logical_capacity=logical_capacity;mirror->bank_size=aligned(sizeof(flash_header_t)+logical_capacity,raw->erase_size?raw->erase_size:1u);if(raw->capacity<mirror->bank_size*2u)return LS_ENOSPACE;flash_header_t first,second;bool first_valid=valid_bank(mirror,0,&first),second_valid=valid_bank(mirror,1,&second);if(first_valid||second_valid){if(second_valid&&(!first_valid||(int32_t)(second.generation-first.generation)>0)){mirror->active_bank=1;mirror->generation=second.generation;}else{mirror->active_bank=0;mirror->generation=first.generation;}}else{ls_memset(workspace,0xff,logical_capacity);ls_result_t result=commit_image(mirror,0,1);if(result!=LS_OK)return result;}mirror->backend=(ls_storage_backend_t){"flash-mirror",mirror,logical_capacity,raw->erase_size,raw->write_size,mirror_read,mirror_write,mirror_erase,mirror_sync};return LS_OK;}
