#include "../core/internal.h"
#include "laststate/flash_storage.h"
#define WEAR_MAGIC 0x574c534cu
#define WEAR_COMMITTED 0xa5u
typedef struct {uint32_t magic,generation,erase_count,data_crc,header_crc;uint8_t committed,reserved[11];} wear_header_t;
static size_t aligned(size_t value,size_t alignment){return alignment?((value+alignment-1u)/alignment)*alignment:value;}
size_t ls_flash_wear_physical_size(size_t logical_capacity,size_t erase_size,size_t slots){if(slots<2u||slots>LS_FLASH_WEAR_MAX_SLOTS)return 0;return aligned(sizeof(wear_header_t)+logical_capacity,erase_size?erase_size:1u)*slots;}
static size_t slot_offset(const ls_flash_wear_level_t *wear,size_t slot){return slot*wear->slot_size;}
static uint32_t header_crc(const wear_header_t *header){return ls_crc32(header,offsetof(wear_header_t,header_crc));}
static bool valid_slot(ls_flash_wear_level_t *wear,size_t slot,wear_header_t *header){size_t offset=slot_offset(wear,slot);if(wear->raw->read(wear->raw->context,offset,header,sizeof *header)!=LS_OK||header->magic!=WEAR_MAGIC||header->committed!=WEAR_COMMITTED||header->header_crc!=header_crc(header))return false;if(wear->raw->read(wear->raw->context,offset+sizeof *header,wear->workspace,wear->logical_capacity)!=LS_OK)return false;return header->data_crc==ls_crc32(wear->workspace,wear->logical_capacity);}
static size_t next_slot(const ls_flash_wear_level_t *wear){size_t selected=(wear->active_slot+1u)%wear->slot_count;uint32_t minimum=UINT32_MAX;for(size_t step=1;step<=wear->slot_count;step++){size_t slot=(wear->active_slot+step)%wear->slot_count;if(slot==wear->active_slot)continue;if(wear->erase_counts[slot]<minimum){minimum=wear->erase_counts[slot];selected=slot;}}return selected;}
static ls_result_t commit(ls_flash_wear_level_t *wear,size_t slot,uint32_t generation){size_t offset=slot_offset(wear,slot);ls_result_t result=wear->raw->erase(wear->raw->context,offset,wear->slot_size);if(result!=LS_OK){wear->failed_commits++;return result;}wear->erase_counts[slot]++;wear_header_t header;ls_memset(&header,0xff,sizeof header);header.magic=WEAR_MAGIC;header.generation=generation;header.erase_count=wear->erase_counts[slot];header.data_crc=ls_crc32(wear->workspace,wear->logical_capacity);header.header_crc=header_crc(&header);result=wear->raw->write(wear->raw->context,offset,&header,sizeof header);if(result==LS_OK)result=wear->raw->write(wear->raw->context,offset+sizeof header,wear->workspace,wear->logical_capacity);if(result==LS_OK){uint8_t committed=WEAR_COMMITTED;result=wear->raw->write(wear->raw->context,offset+offsetof(wear_header_t,committed),&committed,1u);}if(result==LS_OK&&wear->raw->sync)result=wear->raw->sync(wear->raw->context);if(result==LS_OK){wear->active_slot=(uint8_t)slot;wear->generation=generation;}else wear->failed_commits++;return result;}
static ls_result_t read_active(ls_flash_wear_level_t *wear,void *destination){return wear->raw->read(wear->raw->context,slot_offset(wear,wear->active_slot)+sizeof(wear_header_t),destination,wear->logical_capacity);}
static ls_result_t wear_read(void *context,size_t offset,void *destination,size_t length){ls_flash_wear_level_t *wear=(ls_flash_wear_level_t *)context;if(!wear||(!destination&&length)||offset>wear->logical_capacity||length>wear->logical_capacity-offset)return LS_EINVAL;return wear->raw->read(wear->raw->context,slot_offset(wear,wear->active_slot)+sizeof(wear_header_t)+offset,destination,length);}
static ls_result_t update(ls_flash_wear_level_t *wear,size_t offset,const void *source,size_t length,bool erase){if(!wear||(!source&&!erase&&length)||offset>wear->logical_capacity||length>wear->logical_capacity-offset)return LS_EINVAL;ls_result_t result=read_active(wear,wear->workspace);if(result!=LS_OK)return result;if(erase)ls_memset(wear->workspace+offset,0xff,length);else if(length)ls_memcpy(wear->workspace+offset,source,length);return commit(wear,next_slot(wear),wear->generation+1u);}
static ls_result_t wear_write(void *context,size_t offset,const void *source,size_t length){return update((ls_flash_wear_level_t *)context,offset,source,length,false);}
static ls_result_t wear_erase(void *context,size_t offset,size_t length){return update((ls_flash_wear_level_t *)context,offset,0,length,true);}
static ls_result_t wear_sync(void *context){ls_flash_wear_level_t *wear=(ls_flash_wear_level_t *)context;return wear->raw->sync?wear->raw->sync(wear->raw->context):LS_OK;}
ls_result_t ls_flash_wear_init(ls_flash_wear_level_t *wear,ls_storage_backend_t *raw,uint8_t *workspace,size_t logical_capacity,size_t slots){if(!wear||!raw||!raw->read||!raw->write||!raw->erase||!workspace||!logical_capacity||slots<2u||slots>LS_FLASH_WEAR_MAX_SLOTS)return LS_EINVAL;ls_memset(wear,0,sizeof *wear);wear->raw=raw;wear->workspace=workspace;wear->logical_capacity=logical_capacity;wear->slot_count=slots;wear->slot_size=aligned(sizeof(wear_header_t)+logical_capacity,raw->erase_size?raw->erase_size:1u);if(raw->capacity<wear->slot_size*slots)return LS_ENOSPACE;bool found=false;wear_header_t newest;ls_memset(&newest,0,sizeof newest);for(size_t slot=0;slot<slots;slot++){wear_header_t header;ls_memset(&header,0xff,sizeof header);bool valid=valid_slot(wear,slot,&header);if(header.magic==WEAR_MAGIC&&header.header_crc==header_crc(&header))wear->erase_counts[slot]=header.erase_count;if(valid&&(!found||(int32_t)(header.generation-newest.generation)>0)){found=true;newest=header;wear->active_slot=(uint8_t)slot;wear->generation=header.generation;}}if(!found){ls_memset(workspace,0xff,logical_capacity);ls_result_t result=commit(wear,0,1u);if(result!=LS_OK)return result;}wear->backend=(ls_storage_backend_t){"flash-wear-level",wear,logical_capacity,1u,1u,wear_read,wear_write,wear_erase,wear_sync};return LS_OK;}
ls_flash_wear_stats_t ls_flash_wear_stats(const ls_flash_wear_level_t *wear){ls_flash_wear_stats_t stats={0};if(!wear)return stats;stats.generation=wear->generation;stats.failed_commits=wear->failed_commits;stats.slots=wear->slot_count;stats.active_slot=wear->active_slot;stats.minimum_erases=UINT32_MAX;for(size_t i=0;i<wear->slot_count;i++){uint32_t count=wear->erase_counts[i];stats.total_erases+=count;if(count<stats.minimum_erases)stats.minimum_erases=count;if(count>stats.maximum_erases)stats.maximum_erases=count;}if(!wear->slot_count)stats.minimum_erases=0;return stats;}
