#include "../core/internal.h"
#include "laststate/envelope.h"

typedef struct {uint32_t magic;uint16_t version,slots;uint32_t next_sequence,crc;} spool_header_t;
typedef struct {uint32_t magic,sequence;uint16_t length;uint8_t priority,state,event_type,retries;uint16_t reserved;uint32_t crc;} spool_record_t;
enum { RECORD_EMPTY=0xff,RECORD_PENDING=0xa5,RECORD_ACKED=0x00,RECORD_MAGIC=0x4c535245u };
static size_t slot_size(void){return sizeof(spool_record_t)+LS_MAX_EVENT_SIZE;}
static size_t header_size(void){return sizeof(spool_header_t);}
static size_t slot_offset(size_t index){return header_size()+index*slot_size();}
size_t ls_spool_storage_size(void){return header_size()+LS_SPOOL_MAX_RECORDS*slot_size();}
size_t ls_storage_required_size(void){return ls_spool_storage_size()+sizeof(ls_persistent_boot_t);}
static bool usable(void){return ls_runtime.storage&&ls_runtime.storage->read&&ls_runtime.storage->write&&ls_runtime.storage->capacity>=ls_spool_storage_size();}
static ls_result_t read_header(spool_header_t *header){return ls_runtime.storage->read(ls_runtime.storage->context,0,header,sizeof *header);}
static ls_result_t write_header(void){spool_header_t header={LS_STORAGE_MAGIC,LS_FORMAT_VERSION,LS_SPOOL_MAX_RECORDS,ls_runtime.sequence,0};header.crc=ls_crc32(&header,offsetof(spool_header_t,crc));return ls_runtime.storage->write(ls_runtime.storage->context,0,&header,sizeof header);}
ls_result_t ls_spool_init(void){if(!usable())return ls_runtime.storage?LS_ENOSPACE:LS_OK;spool_header_t header;if(read_header(&header)!=LS_OK||header.magic!=LS_STORAGE_MAGIC||header.version!=LS_FORMAT_VERSION||header.slots!=LS_SPOOL_MAX_RECORDS||header.crc!=ls_crc32(&header,offsetof(spool_header_t,crc))){if(!ls_runtime.storage->erase)return LS_ECORRUPT;ls_result_t result=ls_runtime.storage->erase(ls_runtime.storage->context,0,ls_runtime.storage->capacity);if(result!=LS_OK)return result;ls_runtime.sequence=0;return write_header();}ls_runtime.sequence=header.next_sequence;return LS_OK;}
static size_t choose_slot(ls_priority_t priority){size_t empty=LS_SPOOL_MAX_RECORDS,candidate=LS_SPOOL_MAX_RECORDS;spool_record_t oldest={0};for(size_t i=0;i<LS_SPOOL_MAX_RECORDS;i++){spool_record_t record;if(ls_runtime.storage->read(ls_runtime.storage->context,slot_offset(i),&record,sizeof record)!=LS_OK)continue;if(record.magic!=RECORD_MAGIC||record.state!=RECORD_PENDING){empty=i;break;}if(record.priority>(uint8_t)priority&&(candidate==LS_SPOOL_MAX_RECORDS||record.priority>oldest.priority||(record.priority==oldest.priority&&record.sequence<oldest.sequence))){candidate=i;oldest=record;}else if(record.priority==(uint8_t)priority&&priority>=LS_PRIORITY_WARNING&&(candidate==LS_SPOOL_MAX_RECORDS||record.sequence<oldest.sequence)){candidate=i;oldest=record;}}return empty<LS_SPOOL_MAX_RECORDS?empty:candidate;}
ls_result_t ls_spool_append(const uint8_t *data,size_t length,ls_priority_t priority){if(!data||!length||length>LS_MAX_EVENT_SIZE)return LS_EINVAL;if(!usable())return ls_runtime.storage?LS_ENOSPACE:LS_OK;ls_envelope_info_t info;if(ls_envelope_validate(data,length,&info)!=LS_OK)return LS_ECORRUPT;size_t slot=choose_slot(priority);if(slot==LS_SPOOL_MAX_RECORDS)return LS_ENOSPACE;spool_record_t record={RECORD_MAGIC,++ls_runtime.sequence,(uint16_t)length,(uint8_t)priority,RECORD_EMPTY,info.type,0,0,ls_crc32(data,length)};ls_result_t result=ls_runtime.storage->write(ls_runtime.storage->context,slot_offset(slot),&record,sizeof record);if(result==LS_OK)result=ls_runtime.storage->write(ls_runtime.storage->context,slot_offset(slot)+sizeof record,data,length);if(result==LS_OK){record.state=RECORD_PENDING;result=ls_runtime.storage->write(ls_runtime.storage->context,slot_offset(slot),&record,sizeof record);}if(result==LS_OK)result=write_header();if(result==LS_OK&&ls_runtime.storage->sync)result=ls_runtime.storage->sync(ls_runtime.storage->context);return result;}
ls_result_t ls_spool_flush(void){if(!usable())return ls_runtime.storage?LS_ENOSPACE:LS_OK;for(size_t i=0;i<LS_SPOOL_MAX_RECORDS;i++){spool_record_t record;if(ls_runtime.storage->read(ls_runtime.storage->context,slot_offset(i),&record,sizeof record)!=LS_OK||record.magic!=RECORD_MAGIC||record.state!=RECORD_PENDING)continue;if(!record.length||record.length>LS_MAX_EVENT_SIZE){record.state=RECORD_ACKED;(void)ls_runtime.storage->write(ls_runtime.storage->context,slot_offset(i),&record,sizeof record);continue;}uint8_t data[LS_MAX_EVENT_SIZE];if(ls_runtime.storage->read(ls_runtime.storage->context,slot_offset(i)+sizeof record,data,record.length)!=LS_OK||record.crc!=ls_crc32(data,record.length)){record.state=RECORD_ACKED;(void)ls_runtime.storage->write(ls_runtime.storage->context,slot_offset(i),&record,sizeof record);continue;}ls_envelope_info_t info;if(ls_envelope_validate(data,record.length,&info)!=LS_OK)continue;ls_transport_backend_t *transport=ls_transport_select((ls_priority_t)record.priority,record.length);if(!transport)return LS_EAGAIN;ls_result_t result=ls_transport_send(transport,info.event_id,data,record.length);if(result!=LS_OK){if(record.retries<255)record.retries++;(void)ls_runtime.storage->write(ls_runtime.storage->context,slot_offset(i),&record,sizeof record);return result;}record.state=RECORD_ACKED;result=ls_runtime.storage->write(ls_runtime.storage->context,slot_offset(i),&record,sizeof record);if(result!=LS_OK)return result;}return ls_runtime.storage->sync?ls_runtime.storage->sync(ls_runtime.storage->context):LS_OK;}
ls_result_t ls_flush(void){return ls_spool_flush();}
