name: Dependency vulnerability bot
on:
  push:
    branches: [prod]
  pull_request:
  merge_group:
  schedule:
    - cron: '47 8 * * 4'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  scan-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Scan dependencies for known vulnerabilities
        uses: google/osv-scanner-action/osv-scanner-action@a82132c0bd6c7261ffcb78e754c46c70ab57ad9a
        with:
          scan-args: |-
            --recursive
            ./
