name: Dependency vulnerability bot
on:
  push:
    branches: [main]
  pull_request:
  merge_group:
  schedule:
    - cron: '47 8 * * 4'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  scan-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Scan dependencies for known vulnerabilities
        uses: google/osv-scanner-action/osv-scanner-action@8dc09193bb540e09b23da07ad7e30bd33bf87018
        with:
          scan-args: |-
            --recursive
            ./
