[platformio]
default_envs = megaatmega2560

[env:megaatmega2560]
platform = atmelavr@5.1.0
board = megaatmega2560
framework = arduino
lib_deps = file://../..
build_flags =
    -DLS_CONSTRAINED_PROFILE=1
    -Werror=shift-count-overflow
